In [2]:
import pandas as pd

data = pd.read_csv('Customers.csv')
data

,CustomerID,Gender,Age,Annual Income ($),Spending Score (1-100),Profession,Work Experience,Family Size
0,1,Male,19,15000,39,Healthcare,1,4
1,2,Male,21,35000,81,Engineer,3,3
2,3,Female,20,86000,6,Engineer,1,1
3,4,Female,23,59000,77,Lawyer,0,2
4,5,Female,31,38000,40,Entertainment,2,6
...,...,...,...,...,...,...,...,...
1995,1996,Female,71,184387,40,Artist,8,7
1996,1997,Female,91,73158,32,Doctor,7,7
1997,1998,Male,87,90961,14,Healthcare,9,2
1998,1999,Male,77,182109,4,Executive,7,2
1999,2000,Male,90,110610,52,Entertainment,5,2

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              2000 non-null   int64
 1   Gender                  2000 non-null   object
 2   Age                     2000 non-null   int64
 3   Annual Income ($)       2000 non-null   int64
 4   Spending Score (1-100)  2000 non-null   int64
 5   Profession              1965 non-null   object
 6   Work Experience         2000 non-null   int64
 7   Family Size             2000 non-null   int64
dtypes: int64(6), object(2)
memory usage: 125.1+ KB

In [3]:
data.describe()

,CustomerID,Age,Annual Income ($),Spending Score (1-100),Work Experience,Family Size
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,48.960000,110731.821500,50.962500,4.102500,3.768500
std,577.494589,28.429747,45739.536688,27.934661,3.922204,1.970749
min,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,500.750000,25.000000,74572.000000,28.000000,1.000000,2.000000
50%,1000.500000,48.000000,110045.000000,50.000000,3.000000,4.000000
75%,1500.250000,73.000000,149092.750000,75.000000,7.000000,5.000000
max,2000.000000,99.000000,189974.000000,100.000000,17.000000,9.000000

In [4]:
data.isnull().sum()

CustomerID                 0
Gender                     0
Age                        0
Annual Income ($)          0
Spending Score (1-100)     0
Profession                35
Work Experience            0
Family Size                0
dtype: int64

In [5]:
data['Profession'] = data['Profession'].fillna("Unknown")

In [16]:
data.loc[0:15,['CustomerID','Gender','Age','Annual Income ($)']]

    CustomerID  Gender  Age  Annual Income ($)
0            1    Male   19              15000
1            2    Male   21              35000
2            3  Female   20              86000
3            4  Female   23              59000
4            5  Female   31              38000
5            6  Female   22              58000
6            7  Female   35              31000
7            8  Female   23              84000
8            9    Male   64              97000
9           10  Female   30              98000
10          11    Male   67               7000
11          12  Female   35              93000
12          13  Female   58              80000
13          14  Female   24              91000
14          15    Male   37              19000
15          16    Male   22              51000

In [7]:
data = data.rename(columns={'Spending Score (1-100)': 'Spending_Score'})

In [8]:
data

,CustomerID,Gender,Age,Annual Income ($),Spending_Score,Profession,Work Experience,Family Size
0,1,Male,19,15000,39,Healthcare,1,4
1,2,Male,21,35000,81,Engineer,3,3
2,3,Female,20,86000,6,Engineer,1,1
3,4,Female,23,59000,77,Lawyer,0,2
4,5,Female,31,38000,40,Entertainment,2,6
...,...,...,...,...,...,...,...,...
1995,1996,Female,71,184387,40,Artist,8,7
1996,1997,Female,91,73158,32,Doctor,7,7
1997,1998,Male,87,90961,14,Healthcare,9,2
1998,1999,Male,77,182109,4,Executive,7,2
1999,2000,Male,90,110610,52,Entertainment,5,2

In [14]:
data.loc[data['Profession'].isin(['Artist', 'Engineer']), ['CustomerID','Profession]]

      CustomerID Profession
1              2   Engineer
2              3   Engineer
5              6     Artist
8              9   Engineer
9             10     Artist
...          ...        ...
1988        1989     Artist
1990        1991     Artist
1993        1994     Artist
1994        1995   Engineer
1995        1996     Artist

[791 rows x 2 columns]

In [17]:
data['Profession'].unique()

array(['Healthcare', 'Engineer', 'Lawyer', 'Entertainment', 'Artist',
       'Executive', 'Doctor', 'Homemaker', 'Marketing', 'Unknown'],
      dtype=object)

In [24]:
data = data.rename(columns={'Annual Income ($)': 'AI'})

In [25]:
data

,CustomerID,Gender,Age,Annual_Income,Spending_Score,Profession,Work Experience,Family Size
0,1,Male,19,15000,39,Healthcare,1,4
1,2,Male,21,35000,81,Engineer,3,3
2,3,Female,20,86000,6,Engineer,1,1
3,4,Female,23,59000,77,Lawyer,0,2
4,5,Female,31,38000,40,Entertainment,2,6
...,...,...,...,...,...,...,...,...
1995,1996,Female,71,184387,40,Artist,8,7
1996,1997,Female,91,73158,32,Doctor,7,7
1997,1998,Male,87,90961,14,Healthcare,9,2
1998,1999,Male,77,182109,4,Executive,7,2
1999,2000,Male,90,110610,52,Entertainment,5,2

In [28]:
data.groupby('Profession').Annual_Income.mean()

Profession
Artist           108776.580065
Doctor           111573.217391
Engineer         111161.240223
Entertainment    110650.333333
Executive        113770.130719
Healthcare       112574.041298
Homemaker        108758.616667
Lawyer           110995.838028
Marketing        107994.211765
Unknown          117233.828571
Name: Annual_Income, dtype: float64

In [29]:
data.drop_duplicates()

,CustomerID,Gender,Age,Annual_Income,Spending_Score,Profession,Work Experience,Family Size
0,1,Male,19,15000,39,Healthcare,1,4
1,2,Male,21,35000,81,Engineer,3,3
2,3,Female,20,86000,6,Engineer,1,1
3,4,Female,23,59000,77,Lawyer,0,2
4,5,Female,31,38000,40,Entertainment,2,6
...,...,...,...,...,...,...,...,...
1995,1996,Female,71,184387,40,Artist,8,7
1996,1997,Female,91,73158,32,Doctor,7,7
1997,1998,Male,87,90961,14,Healthcare,9,2
1998,1999,Male,77,182109,4,Executive,7,2
1999,2000,Male,90,110610,52,Entertainment,5,2