Hii In this file we will learn pandas 

### Pandas is a library that helps you handle tabular data
- Data in Pandas is stored as dataframes, a 2-d structure similar to the tables in excel
- Pandas offers transformations, data cleaning, preprocessing options, and hence pandas library becomes an eminent part of life of DE and DS
- Pandas offers two data abstraction models - Series and DataFrame

In [ ]:
#Series in pandas is a 1-d data. Dataframe is a 2-d data. Other than that we do not have any dimensional data in pandas

In [3]:
import pandas as pd
#A series can be constructed from a list, tuple, a np.1-d array, a dictionary. But a series cannot be constructed from a set.
a = pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
ser1 = pd.Series([3,4,5,6], index = ['row1','row2','row3','row4'], name = "Series1")
ser1

row1    3
row2    4
row3    5
row4    6
Name: Series1, dtype: int64

In [9]:
df = pd.DataFrame([[1,2,3,4,5],[5,6,7]])
df

   0  1  2    3    4
0  1  2  3  4.0  5.0
1  5  6  7  NaN  NaN

In [ ]:
df2=pd.DataFrame(ser1)
df2

In [10]:
df = pd.DataFrame([[1,2,3],[6,7,8],[9,4,3,2,6,8]], index=['row1','row2','row3'], columns = ['col1','col2','col3','col4','col5','col6'])
df

      col1  col2  col3  col4  col5  col6
row1     1     2     3   NaN   NaN   NaN
row2     6     7     8   NaN   NaN   NaN
row3     9     4     3   2.0   6.0   8.0

In [ ]:
df.rename(columns = {'col1':'c1'}, inplace=True)   #inplace=True ensures that a permanent change is done in the variablef

In [11]:
df

      col1  col2  col3  col4  col5  col6
row1     1     2     3   NaN   NaN   NaN
row2     6     7     8   NaN   NaN   NaN
row3     9     4     3   2.0   6.0   8.0

In [12]:
df.isnull()

       col1   col2   col3   col4   col5   col6
row1  False  False  False   True   True   True
row2  False  False  False   True   True   True
row3  False  False  False  False  False  False

In [4]:
data = pd.read_csv('titanic.csv')
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    object
 4   Sex          156 non-null    object
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    object
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     object
 11  Embarked     155 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 14.8+ KB

In [17]:
data.head(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [18]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [19]:
data.describe(include='O')

                           Name   Sex  Ticket Cabin Embarked
count                       156   156     156    31      155
unique                      156     2     145    28        3
top     Braund, Mr. Owen Harris  male  113803  C123        S
freq                          1   100       2     2      110

In [20]:
data.shape

(156, 12)

In [21]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [23]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [24]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             30
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          125
Embarked         1
dtype: int64

In [27]:
data.Sex.unique()

array(['male', 'female'], dtype=object)

In [29]:
data.Sex.value_counts()

Sex
male      100
female     56
Name: count, dtype: int64

In [32]:
data.Sex[3]
data['Sex'][4]

'male'

In [ ]:
### Locaters and Ilocaters
#### Locaters are name based access of rows and columns. If rows are not named, row numbers also work
- df.loc[col_name,row_name]
- df.loc[[list of col names],[list of row names]]
- df.loc[[list of col_ names] start_row:end_row]
#### Ilocaters are index based access of rows and columns. 
- df.loc[col_name,row_name]
- df.loc[[list of col names],[list of row names]]
- df.loc[start_col:end_col, start_row:end_row]
#### Ilocaters are index based access of rows and colu

In [78]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family
0,1,0,3,"Braund, Mr. Owen Harris",male,NaN,1,0,A/5 21171,7.2500,Nothing,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,NaN,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,NaN,0,0,STON/O2. 3101282,7.9250,Nothing,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,NaN,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,NaN,0,0,373450,8.0500,Nothing,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,NaN,1,0,113776,66.6000,C2,S,1
152,153,0,3,"Meo, Mr. Alfonzo",male,NaN,0,0,A.5. 11206,8.0500,Nothing,S,0
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,NaN,0,2,A/5. 851,14.5000,Nothing,S,2
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,Nothing,S,0
155,156,0,1,"Williams, Mr. Charles Duane",male,NaN,0,1,PC 17597,61.3792,Nothing,C,1

In [9]:
len(data)

156

In [8]:
data.loc[120,'Name']

'Hickman, Mr. Stanley George'

In [10]:
data.loc[[1],['Name','Age']]   ## for select multiple column

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0

In [11]:
data.loc[93,:]  ## here if we want to display whole data of specific id

PassengerId                         94
Survived                             0
Pclass                               3
Name           Dean, Mr. Bertram Frank
Sex                               male
Age                               26.0
SibSp                                1
Parch                                2
Ticket                       C.A. 2315
Fare                            20.575
Cabin                              NaN
Embarked                             S
Name: 93, dtype: object

In [13]:
data.loc[4:15,['Name','Age']]  ## here we can do slicing where we can display data of 4id to 15id

                                                 Name   Age
4                            Allen, Mr. William Henry  35.0
5                                    Moran, Mr. James   NaN
6                             McCarthy, Mr. Timothy J  54.0
7                      Palsson, Master. Gosta Leonard   2.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0
11                           Bonnell, Miss. Elizabeth  58.0
12                     Saundercock, Mr. William Henry  20.0
13                        Andersson, Mr. Anders Johan  39.0
14               Vestrom, Miss. Hulda Amanda Adolfina  14.0
15                   Hewlett, Mrs. (Mary D Kingcome)   55.0

In [14]:
data.iloc[[0,34,1],[3,6]] ## iloc is index based selection if we know the name of col we can go with loc

                                                 Name  SibSp
0                             Braund, Mr. Owen Harris      1
34                            Meyer, Mr. Edgar Joseph      1
1   Cumings, Mrs. John Bradley (Florence Briggs Th...      1

In [15]:
# filtering data based on conditional based 

data.loc[data.Age>60,['Name','Survived','Age']]

                               Name  Survived   Age
33            Wheadon, Mr. Edward H         0  66.0
54   Ostby, Mr. Engelhart Cornelius         0  65.0
96        Goldschmidt, Mr. George B         0  71.0
116            Connors, Mr. Patrick         0  70.5

In [20]:
# Find All Passenger Where Sex is female and who are alone
len(data.loc[(data.Sex=='female')&(data.SibSp==0)&(data.Parch==0)&(data.Survived==1),['Name','Sex','SibSp','Parch','Survived']])

18

In [ ]:
- Get all names of passengers who boarded at 'Q'
- Get the details of passengers who are traveling alone
- Get the name and survival status of passengers who are traveling alone.
- Get the name and age of female passengers who traveled in 3rd class.

In [22]:
# - Get all names of passengers who boarded at 'Q'
data.loc[(data.Embarked=='Q'),['Name','Embarked']]

                               Name Embarked
5                  Moran, Mr. James        Q
16             Rice, Master. Eugene        Q
22      McGowan, Miss. Anna "Annie"        Q
28    O'Dwyer, Miss. Ellen "Nellie"        Q
32         Glynn, Miss. Mary Agatha        Q
44    Devaney, Miss. Margaret Delia        Q
46                Lennon, Mr. Denis        Q
47        O'Driscoll, Miss. Bridget        Q
82   McDermott, Miss. Brigdet Delia        Q
109             Moran, Miss. Bertha        Q
116            Connors, Mr. Patrick        Q
126             McMahon, Mr. Martin        Q
143             Burke, Mr. Jeremiah        Q

In [23]:
#- Get the details of passengers who are traveling alone

data.loc[(data.SibSp==0)&(data.Parch==0),['Name']]

                                             Name
2                          Heikkinen, Miss. Laina
4                        Allen, Mr. William Henry
5                                Moran, Mr. James
6                         McCarthy, Mr. Timothy J
11                       Bonnell, Miss. Elizabeth
..                                            ...
146  Andersson, Mr. August Edvard ("Wennerstrom")
149             Byles, Rev. Thomas Roussel Davids
150                    Bateman, Rev. Robert James
152                              Meo, Mr. Alfonzo
154                         Olsen, Mr. Ole Martin

[85 rows x 1 columns]

In [28]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

pd.reset_option('display.max_rows',None)
pd.reset_option('display.max_columns',None)

In [26]:
# - Get the name and survival status of passengers who are traveling alone.

data.loc[(data.SibSp==0)&(data.Parch==0),['Name','Survived']]

                                             Name  Survived
2                          Heikkinen, Miss. Laina         1
4                        Allen, Mr. William Henry         0
5                                Moran, Mr. James         0
6                         McCarthy, Mr. Timothy J         0
11                       Bonnell, Miss. Elizabeth         1
12                 Saundercock, Mr. William Henry         0
14           Vestrom, Miss. Hulda Amanda Adolfina         0
15               Hewlett, Mrs. (Mary D Kingcome)          1
17                   Williams, Mr. Charles Eugene         1
19                        Masselmani, Mrs. Fatima         1
20                           Fynney, Mr. Joseph J         0
21                          Beesley, Mr. Lawrence         1
22                    McGowan, Miss. Anna "Annie"         1
23                   Sloper, Mr. William Thompson         1
26                        Emir, Mr. Farred Chehab         0
28                  O'Dwyer, Miss. Ellen "Nellie"         1
29                            Todoroff, Mr. Lalio         0
30                       Uruchurtu, Don. Manuel E         0
32                       Glynn, Miss. Mary Agatha         1
33                          Wheadon, Mr. Edward H         0
36                               Mamee, Mr. Hanna         1
37                       Cann, Mr. Ernest Charles         0
42                            Kraeff, Mr. Theodor         0
44                  Devaney, Miss. Margaret Delia         1
45                       Rogers, Mr. William John         0
47                      O'Driscoll, Miss. Bridget         1
51                   Nosworthy, Mr. Richard Cater         0
55                              Woolner, Mr. Hugh         1
56                              Rugg, Miss. Emily         1
57                            Novel, Mr. Mansouer         0
60                          Sirayanian, Mr. Orsen         0
61                            Icard, Miss. Amelie         1
64                          Stewart, Mr. Albert A         0
66                   Nye, Mrs. (Elizabeth Ramell)         1
67                       Crease, Mr. Ernest James         0
70                     Jenkin, Mr. Stephen Curnow         0
72                           Hood, Mr. Ambrose Jr         0
74                                  Bing, Mr. Lee         1
75                        Moen, Mr. Sigurd Hansen         0
76                              Staneff, Mr. Ivan         0
77                       Moutal, Mr. Rahamin Haim         0
79                       Dowdell, Miss. Elizabeth         1
80                           Waelens, Mr. Achille         0
81                    Sheerlinck, Mr. Jan Baptist         1
82                 McDermott, Miss. Brigdet Delia         1
83                        Carrau, Mr. Francisco M         0
84                            Ilett, Miss. Bertha         1
87                  Slocovski, Mr. Selman Francis         0
89                         Celotti, Mr. Francesco         0
90                           Christmann, Mr. Emil         0
91                     Andreasson, Mr. Paul Edvin         0
94                              Coxon, Mr. Daniel         0
95                    Shorney, Mr. Charles Joseph         0
96                      Goldschmidt, Mr. George B         0
100                       Petranec, Miss. Matilda         0
101              Petroff, Mr. Pastcho ("Pentcho")         0
103                    Johansson, Mr. Gustaf Joel         0
105                         Mionoff, Mr. Stoytcho         0
106              Salkjelsvik, Miss. Anna Kristine         1
107                        Moss, Mr. Albert Johan         1
108                               Rekic, Mr. Tido         0
110                Porter, Mr. Walter Chamberlain         0
112                        Barton, Mr. David John         0
114                         Attalah, Miss. Malake         0
115                         Pekoniemi, Mr. Edvard         0
116                          Connors, Mr. Patrick         0
121                    Moore, Mr. Leonard Charles         0
123                           Webber, Miss. Susan         1
126                           McMahon, Mr. Martin         0
127                     Madsen, Mr. Fridtjof Arne         1
129                            Ekstrom, Mr. Johan         0
130                          Drazenoic, Mr. Jozef         0
131                Coelho, Mr. Domingos Fernandeo         0
134                Sobey, Mr. Samuel James Hayden         0
135                            Richard, Mr. Emile         0
138                           Osen, Mr. Olaf Elon         0
139                            Giglio, Mr. Victor         0
141                      Nysten, Miss. Anna Sofia         1
143                           Burke, Mr. Jeremiah         0
144                    Andrew, Mr. Edgardo Samuel         0
146  Andersson, Mr. August Edvard ("Wennerstrom")         1
149             Byles, Rev. Thomas Roussel Davids         0
150                    Bateman, Rev. Robert James         0
152                              Meo, Mr. Alfonzo         0
154                         Olsen, Mr. Ole Martin         0

In [29]:
#- Get the name and age of female passengers who traveled in 3rd class.

data.loc[(data.Sex=='female')&(data.Pclass==3),['Name','Age']]

                                                  Name   Age
2                               Heikkinen, Miss. Laina  26.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
10                     Sandstrom, Miss. Marguerite Rut   4.0
14                Vestrom, Miss. Hulda Amanda Adolfina  14.0
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  31.0
19                             Masselmani, Mrs. Fatima   NaN
22                         McGowan, Miss. Anna "Annie"  15.0
24                       Palsson, Miss. Torborg Danira   8.0
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  38.0
28                       O'Dwyer, Miss. Ellen "Nellie"   NaN
32                            Glynn, Miss. Mary Agatha   NaN
38                  Vander Planke, Miss. Augusta Maria  18.0
39                         Nicola-Yarred, Miss. Jamila  14.0
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  40.0
44                       Devaney, Miss. Margaret Delia  19.0
47                           O'Driscoll, Miss. Bridget   NaN
49       Arnold-Franchi, Mrs. Josef (Josefine Franchi)  18.0
68                     Andersson, Miss. Erna Alexandra  17.0
71                          Goodwin, Miss. Lillian Amy  16.0
79                            Dowdell, Miss. Elizabeth  30.0
82                      McDermott, Miss. Brigdet Delia   NaN
85   Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  33.0
100                            Petranec, Miss. Matilda  28.0
106                   Salkjelsvik, Miss. Anna Kristine  21.0
109                                Moran, Miss. Bertha   NaN
111                               Zabour, Miss. Hileni  14.5
113                            Jussila, Miss. Katriina  20.0
114                              Attalah, Miss. Malake  17.0
119                  Andersson, Miss. Ellis Anna Maria   2.0
128                                  Peter, Miss. Anna   NaN
132     Robins, Mrs. Alexander A (Grace Charity Laury)  47.0
140                      Boulos, Mrs. Joseph (Sultana)   NaN
141                           Nysten, Miss. Anna Sofia  22.0
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...  24.0
147                   Ford, Miss. Robina Maggie "Ruby"   9.0

In [30]:
## Aggregation on a Database

data.groupby('Sex').describe()

       PassengerId                                                      \
             count    mean        std  min    25%   50%     75%    max
Sex
female        56.0  68.125  46.151554  2.0  28.25  58.0  110.50  152.0
male         100.0  84.310  43.785911  1.0  50.50  87.5  121.25  156.0

       Survived            ... Parch        Fare                               \
          count      mean  ...   75%  max  count       mean        std    min
Sex                        ...
female     56.0  0.714286  ...   1.0  5.0   56.0  28.460639  40.144759  7.225
male      100.0  0.140000  ...   0.0  5.0  100.0  27.912998  39.180974  6.750


           25%      50%      75%    max
Sex
female  9.7375  15.9250  26.8500  263.0
male    7.9177  12.0125  34.4448  263.0

[2 rows x 56 columns]

In [31]:
data.groupby('Sex').Age.mean()

Sex
female    24.468085
male      30.326962
Name: Age, dtype: float64

In [44]:
dff = data.groupby('Pclass').agg({
    "Age" : ['min','max','mean'],
    "Fare" : ['min','max','mean'],
    "Survived" : ['sum','count']
})
dff[('non_survived')] = dff[('Survived','count')] - dff[('Survived','sum')]
dff

          Age                      Fare                     Survived        \
          min   max       mean      min       max      mean      sum count
Pclass
1       19.00  71.0  38.111111  26.2833  263.0000  79.50194       12    30
2        0.83  66.0  28.114828  10.5000   73.5000  23.65972       14    30
3        2.00  70.5  24.307143   6.7500   56.4958  13.44006       28    96

       non_survived

Pclass
1                18
2                16
3                68

In [48]:
#Sorting a dataframe
data.sort_values('Age')
data.sort_values('Age',ignore_index=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
1,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
2,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
3,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
4,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
151,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
152,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
153,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
154,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
155,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    object
 4   Sex          156 non-null    object
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    object
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     object
 11  Embarked     155 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 14.8+ KB

In [ ]:
data.Age = data.Age.astype('Int64') ## for change the datatype

In [ ]:
#### Cleaning the data, Manipulating the data
- Transformations
- De-duplication - Removing the duplicates
- Removing columns
- Imputing values

In [52]:
data.drop_duplicates() ## this function will do drop the duplicates data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [ ]:
## data.drop_dupliactes(subset=['colname'])  -- this will do drop duplicates based on colname which we will 

## data.drop_dupliactes(subset=['colname',keep='last'])  -- this will do drop duplicates based on colname and keep the last one drop first dupliacte

In [53]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             30
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          125
Embarked         1
dtype: int64

In [61]:
data.fillna(value={'Cabin':'Nothing','Embarked':'s'},inplace=True)

In [56]:
data['Family'] = data.SibSp + data.Parch ## creating a new column

In [62]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Nothing,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Nothing,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Nothing,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S,1
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,Nothing,S,0
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,Nothing,S,2
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,Nothing,S,0
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,Nothing,C,1

In [63]:
data.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            30
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin           0
Embarked        0
Family          0
dtype: int64

In [76]:
mean_age = data['Age'].mean()
data['Age'] = data['Age'].fillna(mean_age)

In [75]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            156
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         0
Family           0
dtype: int64

In [81]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'PassengerId': [1, 2, 3, 4, 5, 6],
    'Pclass': [1, 3, 2, 1, 3, 2],
    'Age': [22, np.nan, 24, np.nan, 35, 29],
    'Fare': [7.25, 71.83, 8.05, 53.10, 8.46, 13.00],
    'Survived': [0, 1, 1, 1, 0, 0]
})

df

   PassengerId  Pclass   Age   Fare  Survived
0            1       1  22.0   7.25         0
1            2       3   NaN  71.83         1
2            3       2  24.0   8.05         1
3            4       1   NaN  53.10         1
4            5       3  35.0   8.46         0
5            6       2  29.0  13.00         0

In [84]:
df.isnull().sum()

PassengerId    0
Pclass         0
Age            0
Fare           0
Survived       0
dtype: int64

In [83]:
mean_ages = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_ages)

In [85]:
df

   PassengerId  Pclass   Age   Fare  Survived
0            1       1  22.0   7.25         0
1            2       3  27.5  71.83         1
2            3       2  24.0   8.05         1
3            4       1  27.5  53.10         1
4            5       3  35.0   8.46         0
5            6       2  29.0  13.00         0

In [ ]:
data.loc[data['Profession'].isin(['Artist', 'Engineer']), ['CustomerID','Profession']]  ## is in operator use for that profession artist or engineer