In [44]:
## First We have import pandas library and use it as pd 
## then i have use read_csv function of pandas to import csv file and print it
import pandas as pd

data = pd.read_csv("Student_Data_Practice.csv")
data

,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance
0,1001,Student_1,24,Non-binary,Unknown,65.000000,56.000000,61,89.23
1,1002,Student_2,21,Female,Unknown,70.872165,61.000000,81,99.25
2,1003,Student_3,22,Non-binary,Unknown,67.000000,90.000000,81,70.26
3,1004,Student_4,24,Male,Unknown,97.000000,55.000000,77,86.17
4,1005,Student_5,20,Male,Unknown,85.000000,81.000000,62,67.92
...,...,...,...,...,...,...,...,...,...
505,1398,Student_398,21,Male,Unknown,69.000000,47.000000,64,78.34
506,1234,Student_234,22,Male,Unknown,96.000000,65.299587,90,77.38
507,1277,Student_277,24,Male,Unknown,44.000000,67.000000,78,80.51
508,1148,Student_148,23,Female,Unknown,70.000000,40.000000,84,94.23
509,1007,Student_7,22,Male,Unknown,99.000000,40.000000,63,78.56

In [23]:
## Before do anything i have drop the duplicates from data for better work
data.drop_duplicates()

,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance_%
0,1001,Student_1,24,Non-binary,Pune,65.0,56.0,61,89.23
1,1002,Student_2,21,Female,Chennai,NaN,61.0,81,99.25
2,1003,Student_3,22,Non-binary,Chennai,67.0,90.0,81,70.26
3,1004,Student_4,24,Male,Delhi,97.0,55.0,77,86.17
4,1005,Student_5,20,Male,Pune,85.0,81.0,62,67.92
...,...,...,...,...,...,...,...,...,...
495,1496,Student_496,23,Female,Mumbai,50.0,47.0,70,65.38
496,1497,Student_497,18,Male,Hyderabad,91.0,42.0,91,71.98
497,1498,Student_498,21,Male,Delhi,71.0,55.0,75,74.35
498,1499,Student_499,19,Non-binary,Hyderabad,41.0,59.0,93,92.18
499,1500,Student_500,23,Male,Mumbai,86.0,79.0,63,71.15

In [24]:
## Then i took a small tour of our data to know datatypes and little details about our dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   StudentID     510 non-null    int64
 1   Name          510 non-null    object
 2   Age           510 non-null    int64
 3   Gender        510 non-null    object
 4   City          485 non-null    object
 5   Math          485 non-null    float64
 6   Science       484 non-null    float64
 7   English       510 non-null    int64
 8   Attendance_%  510 non-null    float64
dtypes: float64(3), int64(3), object(3)
memory usage: 36.0+ KB

In [45]:
## Then i have use use isnull with sum function to find out how many null values we have in our dataset
data.isnull().sum()

StudentID     0
Name          0
Age           0
Gender        0
City          0
Math          0
Science       0
English       0
Attendance    0
dtype: int64

In [32]:
## Then i got 25 null cites entry in dataset so i have fill it with unknown 
data['City'] = data['City'].fillna("Unknown")
data.to_csv("Student_Data_Practice.csv",index=False)

In [40]:
## Then i have found 25 around null values in maths marks col so i found out the mean of math marks and fill null values with mean number
mean_of_Math = data['Math'].mean()
data['Math'] = data['Math'].fillna(mean_of_Math)

data.to_csv("Student_Data_Practice.csv",index=False)

In [41]:
## Then i have found 25 around null values in Science marks col so i found out the mean of Science marks and fill null values with mean number

mean_of_Science = data['Science'].mean()
data['Science'] = data['Science'].fillna(mean_of_Science)

data.to_csv("Student_Data_Practice.csv",index=False)

In [42]:
data.rename(columns={'Attendance_%': 'Attendance'}, inplace=True)
data.to_csv("Student_Data_Practice.csv",index=False)

In [22]:
data.loc[(data.City=="Mumbai")&(data.Math>80)&(data.Attendance > 75)]

,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance
22,1023,Student_23,19,Female,Mumbai,98.0,49.0,74,81.74
36,1037,Student_37,19,Male,Mumbai,97.0,58.0,95,92.26
61,1062,Student_62,19,Non-binary,Mumbai,81.0,42.0,86,86.27
106,1107,Student_107,22,Male,Mumbai,98.0,47.0,98,82.39
132,1133,Student_133,18,Male,Mumbai,98.0,92.0,68,78.01
178,1179,Student_179,18,Non-binary,Mumbai,94.0,79.0,74,89.60
184,1185,Student_185,24,Male,Mumbai,94.0,48.0,98,90.16
260,1261,Student_261,19,Male,Mumbai,92.0,75.0,64,98.86
278,1279,Student_279,20,Non-binary,Mumbai,86.0,69.0,88,97.27
299,1300,Student_300,21,Male,Mumbai,86.0,55.0,92,98.20
325,1326,Student_326,19,Male,Mumbai,98.0,73.0,55,96.53
354,1355,Student_355,23,Male,Mumbai,95.0,84.0,73,92.90
382,1383,Student_383,24,Female,Mumbai,99.0,76.0,82,99.52
386,1387,Student_387,23,Female,Mumbai,84.0,94.0,96,79.42
396,1397,Student_397,18,Male,Mumbai,92.0,75.0,76,90.25
451,1452,Student_452,19,Non-binary,Mumbai,93.0,99.0,70,91.62
456,1457,Student_457,23,Non-binary,Mumbai,98.0,89.0,79,97.76

In [4]:
data

,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance_%
0,1001,Student_1,24,Non-binary,Pune,65.0,56.0,61,89.23
1,1002,Student_2,21,Female,Chennai,NaN,61.0,81,99.25
2,1003,Student_3,22,Non-binary,Chennai,67.0,90.0,81,70.26
3,1004,Student_4,24,Male,Delhi,97.0,55.0,77,86.17
4,1005,Student_5,20,Male,Pune,85.0,81.0,62,67.92
...,...,...,...,...,...,...,...,...,...
505,1398,Student_398,21,Male,Pune,69.0,47.0,64,78.34
506,1234,Student_234,22,Male,Pune,96.0,NaN,90,77.38
507,1277,Student_277,24,Male,Hyderabad,44.0,67.0,78,80.51
508,1148,Student_148,23,Female,Chennai,70.0,40.0,84,94.23
509,1007,Student_7,22,Male,Delhi,99.0,40.0,63,78.56

In [9]:
data.City.unique()

array(['Pune', 'Chennai', 'Delhi', 'Hyderabad', nan, 'Bangalore',
       'Mumbai'], dtype=object)

In [12]:
data.Science.groupby(data.Gender).mean()

Gender
Female        66.348101
Male          63.754098
Non-binary    66.118881
Name: Science, dtype: float64

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   StudentID     510 non-null    int64
 1   Name          510 non-null    object
 2   Age           510 non-null    int64
 3   Gender        510 non-null    object
 4   City          485 non-null    object
 5   Math          485 non-null    float64
 6   Science       484 non-null    float64
 7   English       510 non-null    int64
 8   Attendance_%  510 non-null    float64
dtypes: float64(3), int64(3), object(3)
memory usage: 36.0+ KB

In [46]:
data.isnull().sum()

StudentID     0
Name          0
Age           0
Gender        0
City          0
Math          0
Science       0
English       0
Attendance    0
dtype: int64

In [48]:
data['Total_Score'] = data.Math + data.Science + data.English
data['Total_Score']

0      182.000000
1      212.872165
2      238.000000
3      229.000000
4      228.000000
          ...
505    180.000000
506    251.299587
507    189.000000
508    194.000000
509    202.000000
Name: Total_Score, Length: 510, dtype: float64

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StudentID    510 non-null    int64
 1   Name         510 non-null    object
 2   Age          510 non-null    int64
 3   Gender       510 non-null    object
 4   City         510 non-null    object
 5   Math         510 non-null    float64
 6   Science      510 non-null    float64
 7   English      510 non-null    int64
 8   Attendance   510 non-null    float64
 9   Total_Score  510 non-null    float64
dtypes: float64(4), int64(3), object(3)
memory usage: 40.0+ KB

In [53]:
find_id = data['Attendance'].argmin()
find_name = data.loc[find_id, 'Name']
find_name

data.to_csv("Student_Data_Practice.csv", index=False)

In [55]:
import pandas as pd
import numpy as np



scores_matrix = data[['Math','Science','English']].values
scores_matrix

array([[65.        , 56.        , 61.        ],
       [70.87216495, 61.        , 81.        ],
       [67.        , 90.        , 81.        ],
       ...,
       [44.        , 67.        , 78.        ],
       [70.        , 40.        , 84.        ],
       [99.        , 40.        , 63.        ]], shape=(510, 3))

In [57]:
print(f"The Shape Of This 2D Array is :- {scores_matrix.shape}")
print(f"The Diamension Of This 2D Array is :- {scores_matrix.ndim}")

The Shape Of This 2D Array is :- (510, 3)
The Diamension Of This 2D Array is :- 2

In [58]:
scores_matrix.mean()

np.float64(70.30692377771875)

In [60]:
data.to_csv("clean_Student_Data_Practise.csv", index=False)